services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./frontend/app:/app
