services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ~/.ssh:/root/.ssh:ro
    environment:
      - PYTHONUNBUFFERED=1
      - SSH_AUTH_SOCK=/ssh-agent

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./frontend/app/node_modules:/app/node_modules
      - ./frontend/app:/app
